load tag;
load shake;
in1 = tag';
in2 = shake';
subplot(3,1,1);
plot(in1);
grid;
title('The first signal');
subtitle('Team5: NgocNguyen DaiDuc');
subplot(3,1,2);
plot(in2);
grid;
title('The second signal');
subplot(3,1,3);
out = mixer(in1,in2);
plot(out);
sound(out);
grid;
title('The resultant signal');
